[palladium-knight-gaia]
id = 900001107
set = "palladium"
name = "Palladium Knight Gaia"
type = "monster effect"
attribute = "light"
race = "warrior"
level = 7
atk = 2300
def = 2100
effect = """\
If you control no monsters, or your opponent controls a monster with 2000 or more ATK, \
    you can Special Summon this card (from your hand). \
    You can only Special Summon "{CARD_NAME}" once per turn this way. \
Once per battle, if this card battles an opponent's monster, before damage calculation (Quick Effect): \
    You can change the battle position of that opponent's monster. \
When you Ritual or Fusion Summon a "Palladium" monster, \
    you can banish this card from your GY as 1 of materials. \
"""
strings = ["Change battle position of battling monster"]

[palladium-maiden-isis]
id = 900001110
set = "palladium"
name = "Palladium Maiden Isis"
type = "monster effect"
attribute = "light"
race = "fairy"
level = 4
atk = 800
def = 2000
effect = """\
When your opponent activates a card or effect \
    in response to your "Palladium" monster's effect activation (Quick Effect): \
    You can Tribute this card from your hand or face-up field; \
    negate that effect. \
During your Main Phase: \
    You can change this card from face-up Attack Position to face-up Defense Position; \
    immediately after this effect resolves, look at up to 5 cards from the top of each player's Deck. \
During your Main Phase, while this card is in the GY, except the turn it was sent to the GY: \
    You can target 5 "Palladium" monsters that is banished or in your GY, except "{CARD_NAME}"; \
    shuffle this card and all the targeted cards into the Deck, then draw 1 card. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Look at Deck"]

[palladium-archfiend-gilfer]
id = 900001116
set = "palladium archfiend"
name = "Palladium Archfiend Gilfer"
type = "monster effect"
attribute = "dark"
race = "fiend"
level = 6
atk = 2200
def = 2500
effect = """\
You can Normal Summon this card without Tributing, but send it to the GY during the End Phase. \
You can Special Summon this card (from your GY) by Tributing 1 "Palladium" monster. \
    You can only Special Summon "{CARD_NAME}" once per turn this way. \
If this card is sent to the GY: \
    You can target 1 face-up monster on the field; equip this card to that target. \
    That monster loses 500 ATK and DEF while equipped with this card. \
"""
strings = ["Normal Summon without Tributing"]

[palladium-kuriboh]
id = 900001117
set = "palladium kuriboh"
name = "Palladium Kuriboh"
type = "monster effect"
attribute = "dark"
race = "fiend"
level = 1
atk = 300
def = 200
effect = """\
When you would take damage from a monster (by battle or effect): \
    You can discard this card; You take no damage. \
If this card on the field is destroyed and sent to the GY: \
    For the rest of this turn, you take no battle damage. \
If this card is sent from the hand or field to the GY: \
    You can add 1 "Monster Reborn" from your Deck or GY to your hand. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Affected by effect \"{CARD_NAME}\": take no battle damage"]

[palladium-beast-gazelle]
id = 900001118
set = "palladium"
name = "Palladium Beast Gazelle"
type = "monster effect"
attribute = "dark"
race = "beast"
level = 4
atk = 1500
def = 1200
effect = """\
If this card is Normal or Special Summoned: \
    You can send 1 Level 5 or higher "Palladium" monster from your Deck to the GY; \
    add 1 "Fusion" or "Polymerization" Spell from your Deck or GY to your hand. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. \
If this card is used as material for a Fusion Summon: You can draw 1 card. \
"""
strings = []

[palladium-beast-berfomet]
id = 900001119
set = "palladium"
name = "Palladium Beast Berfomet"
type = "monster effect"
attribute = "dark"
race = "fiend"
level = 5
atk = 1400
def = 1800
effect = """\
You can discard this card; \
    add 1 "Fusion" or "Polymerization" Spell, or 1 Level 4 or lower "Palladium" monster from your Deck or GY to your hand. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
When this card destroys a monster by battle: \
    Inflict damage to your opponent equal to the ATK of the destroyed monster. \
When you Fusion Summon a "Palladium" monster, you can banish this card from your GY as 1 of materials. \
"""
strings = []

[palladium-beast-chimera]
id = 900001120
set = "palladium"
name = "Palladium Beast Chimera"
type = "monster fusion effect"
attribute = "dark"
race = "beast"
level = 6
atk = 2100
def = 1800
effect = """\
"Palladium Beast Gazelle" + "Palladium Beast Berfomet"
A Fusion Summon of this card can only be done with the above materials. \
This card gains effects of material monsters used to Fusion Summon it. \
If this card destroys an opponent's monster by battle, \
    it can make a second attack in a row. \
If this card is destroyed by battle or card effect: \
    You can add to your hand, or Special Summon \
    1 "Palladium Beast Gazelle" or "Palladium Beast Berfomet" \
    that is banished or in your Deck, GY. \
"""
strings = ["Make a second attack in a row"]

[the-palladium-oracles]
id = 900001121
set = "palladium"
name = "The Palladium Oracles"
type = "monster fusion effect"
attribute = "light"
race = "spellcaster"
level = 8
atk = 2800
def = 2300
effect = """\
"Palladium Oracle Mahad" or "Palladium Oracle Mana" + 1 Spellcaster monster
Must first be Fusion Summoned with the above materials. \
"Palladium" Spellcaster monsters you control cannot be destroyed by card effects. \
Your opponent cannot target Spells/Traps you control with card effects, \
    also they cannot be destroyed by your opponent's card effects. \
Once per turn, when a monster declares an attack or a card or effect is activated: \
    You can draw 1 card, then if it was a Spell/Trap, \
    you can Set it, and if it was a Trap or Quick-Play Spell, you can activate it this turn. \
If this card is destroyed by battle or card effect: \
    You can shuffle it into the Extra Deck; \
    You can Special Summon both 1 "Palladium Oracle Mahad" and 1 "Palladium Oracle Mana", \
    that are banished or are in your hand, Deck, GY. \
"""
strings = []

[chaos-eyes-palladium-dragoon]
id = 900001122
set = "chaos palladium"
name = "Chaos-Eyes Palladium Dragoon"
type = "monster fusion effect"
attribute = "light"
race = "spellcaster"
level = 8
atk = 3000
def = 2500
effect = """\
"Palladium Oracle Mahad" + "Blue-Eyes White Dragon" or 1 LIGHT Dragon Effect Monster
Must first be Fusion Summoned with the above materials. \
Cannot be Tributed, or be used as a material for an Summon by your opponent. \
Cannot be destroyed by card effects. Your opponent cannot target it with card effects. \
Once per turn, when another card or effect is activated (Quick Effect): \
    You can discard 1 card; \
    negate the activation, and if you do, destroy that card. \
You can destroy all monsters your opponent controls OR all Spell/Trap they control. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
If this card is Fusion Summoned using an Normal Monster, it gains this effect.
● If this card's effect destroys a card, this card gains 500 ATK for each destroyed card.
"""
strings = [
    "Negate activation, then destroy",
    "Destroy all monster or Spell/Trap",
    "Destroy all monster",
    "Destroy all Spell/Trap",
    "Fusion Summoned with an Normal Monster",
]

[palladium-master-chaos]
id = 900001123
set = "palladium chaos"
name = "Palladium Master of Chaos"
type = "monster fusion effect"
attribute = "dark"
race = "spellcaster"
level = 8
atk = 3000
def = 2500
effect = """\
"Palladium Oracle Mahad" + 1 "Chaos" or "Black Luster Soldier" Ritual Monster
Must first be Fusion Summoned with the above materials. \
If this card is Fusion Summoned: \
    You can add 1 card in your GY to your hand. \
You can Special Summon 1 LIGHT or DARK monster that is banished or is in your GY, \
    except "{CARD_NAME}". \
(Quick Effect): You can Tribute 1 LIGHT and 1 DARK monster; \
    banish all monsters your opponent controls. \
You can only use each effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Add 1 card to your hand",
    "Special Summon 1 LIGHT or DARK monster",
    "Banish monsters your opponent controls",
]

[necromancer-palladium]
id = 900001124
set = "palladium"
name = "Necromancer of Palladium"
type = "monster fusion effect"
attribute = "dark"
race = "spellcaster"
level = 8
atk = 2900
def = 2400
effect = """\
"Palladium Oracle Mahad" + 1 Fiend monster
Must first be Fusion Summoned with the above materials. \
The activation and effect of this card's effects cannot be negated. \
If this card is Special Summoned: \
    You can target any number of Spells/Traps in any GY(s); \
    banish those targets, and if you do, \
    this card gains 100 ATK for each card banished by this effect. \
(Quick Effect): You can send 1 other card you control, \
    then target 1 face-up card your opponent controls; Negate its effects. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = ["Banish Spells/Traps to gain ATK"]

[dark-flare-knight-palladium]
id = 900001125
set = "palladium"
name = "Dark Flare Knight of Palladium"
type = "monster fusion effect"
attribute = "dark"
race = "warrior"
level = 6
atk = 2200
def = 800
effect = """\
1 Level 6 or higher Spellcaster monster + 1 Warrior monster
Must first be Fusion Summoned with the above materials. \
If this card is Special Summoned: \
    You can target 1 card on the field; destroy it. \
Negate the effects of face-up monsters your opponent controls \
    with ATK less than or equal to this card's. \
If this card is destroyed by battle or card effect: \
    You can Special Summon 1 "Palladium" monster from your hand, Deck or GY, \
    except "{CARD_NAME}".
"""
strings = []

[forbidden-art-palladium]
id = 900001129
set = "palladium fusion"
name = "Forbidden Art of Palladium"
type = "spell quick-play"
effect = """\
(This card is always treated as an "Fusion" card.)
You can only activate this card during your Main Phase, unless you control "Palladium Oracle Mahad". \
Activate 1 of these effects.
● Ritual Summon 1 "Palladium" Ritual Monster from your hand or GY, \
    by Tributing monsters from your hand or field, \
    whose total Levels equal or exceed the Level of the Ritual Monster.
● Fusion Summon 1 Fusion Monster from your Extra Deck, \
    using monsters from your hand or field as Fusion Material, including a "Palladium" monster, \
    you can use 1 "Palladium" monster from your Deck as material.
"""
strings = []

[palladium-fusion-mastery]
id = 900001130
alias = 95286165
name = "Palladium Fusion Mastery"
type = "spell quick-play"
effect = """\
(This card's name is always treated as "De-Fusion" and it is "Palladium" card.)
Activate 1 of these effects.
● Target 1 Fusion Monster on the field; return it to the Extra Deck, then, \
    if all the Fusion Materials that were used for its Fusion Summon are banished and/or are in your hand, Deck, GY, \
    you can Special Summon all of them.
● This turn, the activation of your cards and effects that include an effect that Fusion Summons a Fusion Monster cannot be negated, \
    also your opponent cannot activate cards or effects when a monster is Fusion Summoned this way. \
    Your opponent cannot activate cards or effects in response to this effect's activation.
During your Main Phase, while this card is in the GY: \
    You add 1 "Fusion" or "Polymerization" Spell from your Deck or GY to your hand, except "{CARD_NAME}", \
    then return this card to the bottom of the Deck. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = [
    "Special Summon all Fusion Materials?",
    "De-fuse a Fusion Monster",
    "Prevent Fusion Negation",
]

[palladium-swords-revealing-light]
id = 900001131
set = "palladium"
name = "Palladium Swords of Revealing Light"
type = "spell quick-play"
effect = """\
This card can only be activated during Main Phase 1. \
    After this card's activation, it remains on the field. \
    You can only control 1 "{CARD_NAME}". \
When this card is activated: \
    Place 3 Spell Counter on this card (max. 3), \
    also, after that if your opponent controls a face-down monster, \
    flip all monsters they control face-up. Flip Effects are not activated at this time. \
Once per turn, during your opponent's End Phase, \
    remove 1 Spell Counter from this card. \
While this card is face-up on the field with a Spell Counters, \
    your opponent's monsters cannot declare an attack. \
You can send this card with no Spell Counter to the GY; draw 3 cards. \
"""
strings = []

[palladium-sacrophagus]
id = 900001132
set = "palladium"
name = "Palladium Sacrophagus"
type = "spell quick-play"
effect = """\
If you control no monsters, you can activate this card from your hand in either player's turn. \
Banish 1 card from your Deck or in either GY, \
    and if you do, until the end of the next turn, its effects are negated, \
    as well as the activated effects and effects on your opponent's side of the field of cards with the same original name. \
    You can only activate 1 "{CARD_NAME}" per turn. \
During your Main Phase, except the turn this card was sent to the GY: \
    You can return this card to the bottom of the Deck, \
    and if you do, add 1 your face-up banished card to your hand. \
    You can only use this effect of "{CARD_NAME}" once per turn. \
"""
strings = []

[palladium-reborn]
id = 900001133
alias = 83764718
name = "Palladium Reborn"
type = "spell quick-play"
effect = """\
(This card's name is always treated as "Monster Reborn" and it is "Palladium" card.)
During your Main Phase or your opponent's turn: \
    Target 1 monster in either GY; Special Summon that monster. \
You can also Special Summon a monster that can be Normal Summoned with this effect, ignoring its Summoning conditions, \
    but send that monster to the GY during the End Phase. \
"""
strings = []

[palladium-mirror-force]
id = 900001134
set = "palladium"
name = "Palladium Mirror Force"
type = "trap counter"
effect = """\
Activate 1 of these effects.
● When your opponent activates a monster effect that targets a monster(s) you control: \
    Negate that effect, also destroy all your opponent's Attack Position monsters.
● When an opponent's monster declares an attack: \
    Negate that attack, also destroy all your opponent's Attack Position monsters.
If this Set card is destroyed by your opponent's card effect and sent to your GY: \
    You can Set this card from your GY and 1 "Palladium" Trap Card from your hand, Deck, or GY, \
    except "Palladium Mirror Force". They can be activated this turn. \
"""
strings = []

[palladium-shattering-arrow]
id = 900001135
set = "palladium"
name = "Palladium Shattering Arrow"
type = "trap counter"
effect = """\
If you control "Palladium" monster: Activate as Chain Link 2 or higher; \
    negate the activations of your opponent's Spell/Trap Cards and monster effects activated before this card in this Chain, \
    and if you do, destroy the negated cards on the field, \
    also you can apply 1 of those negated effects that targets a card(s). \
If you control "Palladium Oracle Mahad", except the turn this card was sent to the GY: \
    You can return this card from your GY to the bottom of the Deck, \
    then target 1 face-up card your opponent controls; \
    negate its effects until the end of this turn. \
"""
strings = ["Apply 1 of negated effects?"]
